package com.devsquad.project;

public enum ProjectEventType {
    PROJECT_CREATED,
    REQUIREMENTS_COMPLETED,
    ARCHITECTURE_COMPLETED,
    DATABASE_DESIGN_COMPLETED,
    API_DESIGN_COMPLETED,
    SECURITY_SCAN_COMPLETED,
    REVIEW_COMPLETED,
    FIX_REQUIRED,
    RETRY_SCHEDULED,
    TASK_FAILED,
    PROJECT_WAITING_FOR_APPROVAL,
    APPROVAL_GRANTED,
    APPROVAL_REJECTED,
    PROJECT_READY_FOR_IMPLEMENTATION
}